title: Harvard Technology Review
author: Contact Us
email: contact@harvardtechnologyreview.com
description: > # this means to ignore newlines until "twitter_username:"

# social links
twitter_username: harvardtechnologyreview
# github_username: jekyll
# rss: rss
# dribbble_username: jekyll
facebook_username: harvardtechnologyreview
# flickr_username: jekyll
instagram_username: harvardtechnologyreview

show_excerpts: false # set to true to show excerpts on the homepage
baseurl: ""

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- subscribe.md

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag
