title: HARVARD TECH REVIEW
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
 Harvard Tech Review in-progress site.

# social links
twitter_username: jekyllrb
github_username: jekyll
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

show_excerpts: false # set to true to show excerpts on the homepage
baseurl: /techreview

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- subscribe.md

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag
